[tool.poetry]
name = "pynumaflow"
version = "0.12.1"
description = "Provides the interfaces of writing Python User Defined Functions and Sinks for NumaFlow."
authors = ["NumaFlow Developers"]
readme = "README.md"
license = "Apache-2.0"
maintainers = [
    "Avik Basu <avikbasu93@gmail.com>",
    "Vigith Maurice <vigith@gmail.com>",
]
classifiers = [
    "Topic :: Software Development :: Libraries",
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14"
]
repository = "https://github.com/numaproj/numaflow-python"

[tool.poetry.dependencies]
python = ">=3.9, <3.15"
grpcio = "^1.48.1"
grpcio-tools = "^1.48.1"
google-api-core = "^2.11.0"
grpcio-status = "^1.48.1"
protobuf = ">=6.31.1,<7.0"
aiorun = "^2023.7"
uvloop = ">=0.21.0"
psutil = "^6.0.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pytest-cov = "^3.0"
black = "^23.1"
grpcio-testing = "^1.48.1"
ruff = "^0.0.264"
pre-commit = "^3.3.1"
types-protobuf = "^6.32.1.20250918"
mypy = "^1.18.2"
grpc-stubs = "^1.53.0.6"
types-psutil = "^7.0.0.20251001"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6"
mkdocs-material = {version = "^9.5", extras = ["imaging"]}
mkdocs-exclude = "^1.0"
mkdocstrings = {version = "^0.27", extras = ["python"]}
mike = "^2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py39"]
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.idea
  | _build
  | buck-out
  | build
  | dist
  | tests/.*/setup.py
  | function/proto
  | sink/proto
)/
'''

[tool.ruff]
line-length = 100
src = ["pynumaflow", "tests", "examples"]
target-version = "py39"
show-fixes = true
extend-exclude = [
    "*_pb2.py",
    "*_pb2*.py",
    "*.pyi"
]
select = ["E", "F", "UP"]

