apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-sideinput
spec:
  sideInputs:
    - name: myticker
      container:
        image: quay.io/numaio/numaflow/pynumaflow-lite-sideinput:v1
        imagePullPolicy: Never
      trigger:
        schedule: "*/10 * * * * *"
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 1
          duration: 1s
    - name: si-map
      udf:
        container:
          image: quay.io/numaio/numaflow/pynumaflow-lite-sideinput:v1
          imagePullPolicy: Never
          env:
            - name: MAPPER
              value: "true"
      sideInputs:
        - myticker
    - name: out
      sink:
        # A simple log printing sink
        log: { }
  edges:
    - from: in
      to: si-map
    - from: si-map
      to: out

