name: Changelog

on:
  push:
    tags:
      - v*
  pull_request:
    branches: [ "main" ]
jobs:
  generate_changelog:
    if: github.repository == 'numaproj/numaflow-python'
    runs-on: ubuntu-latest
    name: Generate changelog
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - run: ls -la
      - run: git fetch --prune --prune-tags
      - run: git tag -l 'v*'
      - run: ./.hack/changelog.sh > CHANGELOG.md
      - uses: peter-evans/create-pull-request@v3
        with:
          title: 'docs: updated CHANGELOG.md'
          commit-message: 'docs: updated CHANGELOG.md'
          signoff: true
